"""Tough Talks runtime — shared model loading, generation, and parsing.

Imported by every notebook and FastAPI route so model handling stays
consistent. Public surface is intentionally small.
"""

from .aftermath import (
    ALLOWED_GOAL_STATUSES,
    ALLOWED_MATCH_QUALITIES,
    ALLOWED_UNFORESEEN_KINDS,
    AftermathConfig,
    AftermathError,
    DEFAULT_AFTERMATH_PROMPT_NAME,
    build_aftermath_messages,
    format_debrief_block,
    format_premortem_block,
    generate_aftermath,
)
from .audio import (
    DEFAULT_CHUNK_OVERLAP_SECONDS,
    DEFAULT_CHUNK_SECONDS,
    DEFAULT_INSTRUCTION as DEFAULT_TRANSCRIPTION_INSTRUCTION,
    MAX_AUDIO_SECONDS,
    TranscribeConfig,
    build_transcription_messages,
    chunk_audio,
    compute_chunk_windows,
    transcribe,
    transcribe_long,
)
from .debrief import (
    DEFAULT_DEBRIEF_PROMPT_NAME,
    DebriefConfig,
    DebriefError,
    build_debrief_messages,
    count_user_turns,
    format_practice_transcript,
    generate_debrief,
)
from .emotion import (
    ALLOWED_EMOTIONS,
    ALLOWED_SPEAKERS,
    DEFAULT_EMOTION_PROMPT_NAME,
    DEFAULT_PRIOR_CONTEXT_HISTORY,
    EmotionAnalysisError,
    EmotionConfig,
    analyze_emotion,
    analyze_emotion_long,
    build_emotion_messages,
    format_emotion_context,
)
from .generation import GenerationConfig, chat
from .model import DEFAULT_MODEL_ID, LoadConfig, load_model
from .parsing import JsonParseError, parse_json, try_parse_json
from .person_vault import (
    ALLOWED_COMMUNICATION_STYLES,
    ALLOWED_RELATIONSHIP_TYPES,
    DEFAULT_PERSON_NAME,
    DEFAULT_PERSON_VAULT_PROMPT_NAME,
    DEFAULT_RELATIONSHIP_TYPE,
    DeterministicPersonMetrics,
    PersonVaultAnalysisError,
    PersonVaultConfig,
    analyze_person_vault,
    compute_person_metrics,
    format_person_prior_profile,
)
from .persona_sim import (
    ALLOWED_RESISTANCE_TYPES,
    DEFAULT_PERSONA_PROMPT_NAME,
    DEFAULT_USER_GOAL,
    PersonaReplyError,
    PersonaSimConfig,
    build_practice_messages,
    format_persona_profile_block,
    generate_persona_reply,
    run_practice_conversation,
)
from .premortem import (
    DEFAULT_PREMORTEM_PROMPT_NAME,
    PremortemConfig,
    PremortemError,
    REQUIRED_SCENARIO_COUNT,
    build_premortem_messages,
    format_talk_dna_block,
    generate_premortem,
)
from .prompts import Prompt, PromptError, load_prompt
from .pulse import (
    ALLOWED_HEALTH_TRENDS,
    ALLOWED_ROUND_GOAL_STATUSES,
    DEFAULT_PULSE_PROMPT_NAME,
    PulseConfig,
    PulseError,
    ROUND_COUNT_MIN,
    build_pulse_messages,
    format_prior_pulse_block,
    format_rounds_block,
    generate_pulse,
)
from .talk_dna import (
    ALLOWED_SARCASM_FREQUENCIES,
    DEFAULT_TALK_DNA_PROMPT_NAME,
    DEFAULT_USER_ID,
    DeterministicMetrics,
    TalkDNAAnalysisError,
    TalkDNAConfig,
    analyze_talk_dna,
    compute_deterministic_metrics,
    format_prior_profile,
    format_transcript,
)
from .tool_calls import ToolCallParseError, parse_tool_calls
from .tools import ToolSchemaError, load_tools

__all__ = [
    "ALLOWED_COMMUNICATION_STYLES",
    "ALLOWED_EMOTIONS",
    "ALLOWED_GOAL_STATUSES",
    "ALLOWED_HEALTH_TRENDS",
    "ALLOWED_MATCH_QUALITIES",
    "ALLOWED_RELATIONSHIP_TYPES",
    "ALLOWED_RESISTANCE_TYPES",
    "ALLOWED_ROUND_GOAL_STATUSES",
    "ALLOWED_SARCASM_FREQUENCIES",
    "ALLOWED_SPEAKERS",
    "ALLOWED_UNFORESEEN_KINDS",
    "AftermathConfig",
    "AftermathError",
    "DEFAULT_AFTERMATH_PROMPT_NAME",
    "DEFAULT_CHUNK_OVERLAP_SECONDS",
    "DEFAULT_CHUNK_SECONDS",
    "DEFAULT_DEBRIEF_PROMPT_NAME",
    "DEFAULT_EMOTION_PROMPT_NAME",
    "DEFAULT_MODEL_ID",
    "DEFAULT_PERSONA_PROMPT_NAME",
    "DEFAULT_PERSON_NAME",
    "DEFAULT_PERSON_VAULT_PROMPT_NAME",
    "DEFAULT_PREMORTEM_PROMPT_NAME",
    "DEFAULT_PRIOR_CONTEXT_HISTORY",
    "DEFAULT_PULSE_PROMPT_NAME",
    "DEFAULT_RELATIONSHIP_TYPE",
    "DEFAULT_TALK_DNA_PROMPT_NAME",
    "DEFAULT_TRANSCRIPTION_INSTRUCTION",
    "DEFAULT_USER_GOAL",
    "DEFAULT_USER_ID",
    "DebriefConfig",
    "DebriefError",
    "DeterministicMetrics",
    "DeterministicPersonMetrics",
    "EmotionAnalysisError",
    "EmotionConfig",
    "GenerationConfig",
    "JsonParseError",
    "LoadConfig",
    "MAX_AUDIO_SECONDS",
    "PersonaReplyError",
    "PersonaSimConfig",
    "PersonVaultAnalysisError",
    "PersonVaultConfig",
    "PremortemConfig",
    "PremortemError",
    "Prompt",
    "PromptError",
    "PulseConfig",
    "PulseError",
    "REQUIRED_SCENARIO_COUNT",
    "ROUND_COUNT_MIN",
    "TalkDNAAnalysisError",
    "TalkDNAConfig",
    "ToolCallParseError",
    "ToolSchemaError",
    "TranscribeConfig",
    "analyze_emotion",
    "analyze_emotion_long",
    "analyze_person_vault",
    "analyze_talk_dna",
    "build_aftermath_messages",
    "build_debrief_messages",
    "build_emotion_messages",
    "build_practice_messages",
    "build_premortem_messages",
    "build_pulse_messages",
    "build_transcription_messages",
    "chat",
    "chunk_audio",
    "compute_chunk_windows",
    "compute_deterministic_metrics",
    "compute_person_metrics",
    "count_user_turns",
    "format_debrief_block",
    "format_emotion_context",
    "format_persona_profile_block",
    "format_person_prior_profile",
    "format_practice_transcript",
    "format_premortem_block",
    "format_prior_profile",
    "format_prior_pulse_block",
    "format_rounds_block",
    "format_talk_dna_block",
    "format_transcript",
    "generate_aftermath",
    "generate_debrief",
    "generate_persona_reply",
    "generate_premortem",
    "generate_pulse",
    "load_model",
    "load_prompt",
    "load_tools",
    "parse_json",
    "parse_tool_calls",
    "run_practice_conversation",
    "transcribe",
    "transcribe_long",
    "try_parse_json",
]
